var starttour_units=[
  {
    "questionattributes": [
      {
        "id": 1,
        "questionid": 1,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "Please learn to say the sound /ʃ/ found in sure, ship and national",
        "priorities": 1,
        "type": "3",
        "status": "1",
        "groupid": 1,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      }
    ],
    "questionid": 1,
    "question_name": "Sound - /J/",
    "illustrate_img_path": "",
    "img_path": "",
    "video_path": "https://www.youtube.com/watch?v=NF92RdZC6wE",
    "audio_path": "",
    "status": "1",
    "type": "1",
    "answer_type": "",
    "answer_num": 0,
    "ui_type":'1'
  },
  {
    "questionattributes": [
      {
        "id": 2,
        "questionid": 2,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "Show /ʃow/ (v) <br/>to make something clear; to prove something.<br/>show (that)… The figures clearly show that her claims are false.<br/>show somebody that… Market research has shown us that people want quality, not just low prices.",
        "priorities": 1,
        "type": "2",
        "status": "1",
        "groupid": 2,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 3,
        "questionid": 2,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "to make something clear; to prove something",
        "priorities": 2,
        "type": "3",
        "status": "0",
        "groupid": 2,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 4,
        "questionid": 2,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "show (that)… The figures clearly show that her claims are false.\nshow somebody that… Market research has shown us that people want quality, not just low prices.",
        "priorities": 3,
        "type": "3",
        "status": "0",
        "groupid": 2,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      }
    ],
    "questionid": 2,
    "question_name": "Word - Show\r\n",
    "illustrate_img_path": null,
    "img_path": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "video_path": null,
    "audio_path": "audio/00_Start_Tour/01_Words/word_show.mp3\r\n",
    "status": "1",
    "type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "ui_type":'2'
  },
  {
    "questionattributes": [
      {
        "id": 5,
        "questionid": 3,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "So /səʊ/ (adv)\n1. to such a great degree\nDon't look so angry.\nso… (that)… She spoke so quietly (that) I could hardly hear her.\n2. very; extremely\n I'm so glad to see you.",
        "priorities": 1,
        "type": "2",
        "status": "1",
        "groupid": 3,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 6,
        "questionid": 3,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "1. to such a great degree",
        "priorities": 2,
        "type": "3",
        "status": "0",
        "groupid": 3,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 7,
        "questionid": 3,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "Don't look so angry.\nso… (that)… She spoke so quietly (that) I could hardly hear her.",
        "priorities": 3,
        "type": "3",
        "status": "0",
        "groupid": 3,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 8,
        "questionid": 3,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "2. very; extremely",
        "priorities": 4,
        "type": "3",
        "status": "0",
        "groupid": 3,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 9,
        "questionid": 3,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "I'm so glad to see you.",
        "priorities": 5,
        "type": "3",
        "status": "0",
        "groupid": 3,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      }
    ],
    "questionid": 3,
    "question_name": "Word - So\r\n",
    "illustrate_img_path": null,
    "img_path": null,
    "video_path": null,
    "audio_path": null,
    "status": "1",
    "type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "ui_type":'2'
  },
  {
    "questionattributes": [
      {
        "id": 21,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "my Christmas",
        "priorities": 1,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 22,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "to go shopping",
        "priorities": 2,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 23,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "finished",
        "priorities": 3,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
     {
        "id": 24,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "with me",
        "priorities": 4,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 25,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "this weekend?",
        "priorities": 5,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 26,
        "questionid": 15,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "Well, I still haven't",
        "priorities": 6,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 27,
        "questionid": 15,
        "attributeid": 2,
        "attribute_name": "Question answer",
        "attribute_value": "Well, I still haven't finished my Christmas shopping. Do you want to go shopping with me this weekend?",
        "priorities": 1,
        "type": "2",
        "status": "1",
        "groupid": 1,
        "ui_type": "4",
        "att_code": "QUESTION_ANSWER\r\n"
      }
    ],
    "questionid": 15,
    "question_name": "Start tour Listen and Write",
    "illustrate_img_path": "",
    "img_path": "",
    "video_path": "",
    "audio_path": "audio/00_Start_Tour/03_Listening/48_03.mp3",
    "status": "1",
    "type": "5",
    "answer_type": "3",
    "answer_num": 1,
    "ui_type":'4'
  },
  {
    "questionattributes": [
      {
        "id": 28,
        "questionid": 16,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "An Memo\n To: Supervisors\nFrom: Judy Linquiest, Human Resource Manager\nSub: Probation periods\n\nAs of January 1st all new employees will be subject to a 3 month probationary period. Medical, holiday, and flextime benefits will not apply to new staff members until the full 3 months have expired.\n After the three months have been completed, please contact your employees and inform them that their probationary period has ended. The HR department will contact you by email 2 days in advance to remind you of the date.\nThank you for your cooperation.",
        "priorities": 1,
        "type": "6",
        "status": "1",
        "groupid": 1,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      }
    ],
    "questionid": 16,
    "question_name": "Start tourReading",
    "illustrate_img_path": "",
    "img_path": "",
    "video_path": "",
    "audio_path": "",
    "status": "1",
    "type": "6",
    "answer_type": "4",
    "answer_num": 1,
    "ui_type":'5'
  },
  {
    "questionattributes": [
      {
        "id": 29,
        "questionid": 17,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "What is the main purpose of this memo?",
        "priorities": 1,
        "type": "3",
        "status": "1",
        "groupid": 1,
        "ui_type": "1",
        "att_code": "QUESTION_CONTENT"
      },
      {
        "id": 30,
        "questionid": 17,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "To inform all employees of a new expiration date.",
        "priorities": 2,
        "type": "3",
        "status": "1",
        "groupid": 2,
        "ui_type": "2",
        "att_code": "QUESTION_CHOICE"
      },
      {
        "id": 31,
        "questionid": 17,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": " To put staff members on probation.",
        "priorities": 3,
        "type": "3",
        "status": "1",
        "groupid": 2,
        "ui_type": "2",
        "att_code": "QUESTION_CHOICE"
      },
      {
        "id": 32,
        "questionid": 17,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "To introduce the HR department.",
        "priorities": 4,
        "type": "3",
        "status": "1",
        "groupid": 2,
        "ui_type": "2",
        "att_code": "QUESTION_CHOICE"
      },
      {
        "id": 33,
        "questionid": 17,
        "attributeid": 1,
        "attribute_name": "Question content",
        "attribute_value": "To inform supervisors of a change in policy.",
        "priorities": 5,
        "type": "3",
        "status": "1",
        "groupid": 2,
        "ui_type": "2",
        "att_code": "QUESTION_CHOICE"
      },
      {
        "id": 34,
        "questionid": 17,
        "attributeid": 2,
        "attribute_name": "Question answer",
        "attribute_value": "To inform supervisors of a change in policy.",
        "priorities": 1,
        "type": "2",
        "status": "1",
        "groupid": 2,
        "ui_type": "1",
        "att_code": "QUESTION_ANSWER"
      }
    ],
    "questionid": 17,
    "question_name": "Start tourReading -  Question",
    "illustrate_img_path": "",
    "img_path": "",
    "video_path": "",
    "audio_path": "",
    "status": "1",
    "type": "6",
    "answer_type": "",
    "answer_num": 1,
    "ui_type":'6'
  }
]
