var starttour_units=[
  {
    "lessonid": 1,
    "num_unit": 10,
    "unit_priorities": 1,
    "unit_name": "Start tour - Word\r\n",
    "total_point_unit": 100,
    "unit_mandatory": "1",
    "unit_image": null,
    "bonus_point_unit": 0,
    "pass_point_unit": 50,
    "unitid": 1,
    "num_question": 1,
    "num_quest_fail_continue": 5,
    "num_question_fail": 9,
    "question_priorities": 2,
    "question_name": "Word - Show\r\n",
    "question_image": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "question_mandatory": "1",
    "answer_input": {
      "type": "Buffer",
      "data": [
        1
      ]
    },
    "num_answer_fail": 5,
    "total_point_question": 100,
    "bonus_point_question": 0,
    "pass_point_question": 0,
    "ui_type": "2",
    "questionid": 2,
    "illustrate_img_path": null,
    "img_path_quest_other": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "video_path": null,
    "audio_path": "audio/00_Start_Tour/01_Words/word_show.mp3\r\n",
    "question_type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "description": null,
    "question_content": "Please learn to say the sound /ʃ/ found in sure, ship and national\r\n",
    "question_content_prio": 1,
    "quest_content_type": "3",
    "quest_content_groupid": null,
    "quest_content_ui": "1",
    "answer_content": ""
  },
  {
    "lessonid": 1,
    "num_unit": 10,
    "unit_priorities": 1,
    "unit_name": "Start tour - Word\r\n",
    "total_point_unit": 100,
    "unit_mandatory": "1",
    "unit_image": null,
    "bonus_point_unit": 0,
    "pass_point_unit": 50,
    "unitid": 1,
    "num_question": 1,
    "num_quest_fail_continue": 5,
    "num_question_fail": 9,
    "question_priorities": 2,
    "question_name": "Word - Show\r\n",
    "question_image": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "question_mandatory": "1",
    "answer_input": {
      "type": "Buffer",
      "data": [
        1
      ]
    },
    "num_answer_fail": 5,
    "total_point_question": 100,
    "bonus_point_question": 0,
    "pass_point_question": 0,
    "ui_type": "2",
    "questionid": 2,
    "illustrate_img_path": null,
    "img_path_quest_other": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "video_path": null,
    "audio_path": "audio/00_Start_Tour/01_Words/word_show.mp3\r\n",
    "question_type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "description": null,
    "question_content": "Show /ʃow/ (v)\r\n",
    "question_content_prio": 1,
    "quest_content_type": "2",
    "quest_content_groupid": null,
    "quest_content_ui": "1",
    "answer_content": ""
  },
  {
    "lessonid": 1,
    "num_unit": 10,
    "unit_priorities": 1,
    "unit_name": "Start tour - Word\r\n",
    "total_point_unit": 100,
    "unit_mandatory": "1",
    "unit_image": null,
    "bonus_point_unit": 0,
    "pass_point_unit": 50,
    "unitid": 1,
    "num_question": 1,
    "num_quest_fail_continue": 5,
    "num_question_fail": 9,
    "question_priorities": 2,
    "question_name": "Word - Show\r\n",
    "question_image": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "question_mandatory": "1",
    "answer_input": {
      "type": "Buffer",
      "data": [
        1
      ]
    },
    "num_answer_fail": 5,
    "total_point_question": 100,
    "bonus_point_question": 0,
    "pass_point_question": 0,
    "ui_type": "2",
    "questionid": 2,
    "illustrate_img_path": null,
    "img_path_quest_other": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "video_path": null,
    "audio_path": "audio/00_Start_Tour/01_Words/word_show.mp3\r\n",
    "question_type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "description": null,
    "question_content": "to make something clear; to prove something\r\n",
    "question_content_prio": 2,
    "quest_content_type": "3",
    "quest_content_groupid": null,
    "quest_content_ui": "1",
    "answer_content": ""
  },
  {
    "lessonid": 1,
    "num_unit": 10,
    "unit_priorities": 1,
    "unit_name": "Start tour - Word\r\n",
    "total_point_unit": 100,
    "unit_mandatory": "1",
    "unit_image": null,
    "bonus_point_unit": 0,
    "pass_point_unit": 50,
    "unitid": 1,
    "num_question": 1,
    "num_quest_fail_continue": 5,
    "num_question_fail": 9,
    "question_priorities": 2,
    "question_name": "Word - Show\r\n",
    "question_image": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "question_mandatory": "1",
    "answer_input": {
      "type": "Buffer",
      "data": [
        1
      ]
    },
    "num_answer_fail": 5,
    "total_point_question": 100,
    "bonus_point_question": 0,
    "pass_point_question": 0,
    "ui_type": "2",
    "questionid": 2,
    "illustrate_img_path": null,
    "img_path_quest_other": "image/00_Start_Tour/01_Words/word_show.gif\r\n",
    "video_path": null,
    "audio_path": "audio/00_Start_Tour/01_Words/word_show.mp3\r\n",
    "question_type": "2",
    "answer_type": "1",
    "answer_num": 1,
    "description": null,
    "question_content": "\"show (that)… The figures clearly show that her claims are false.\nshow somebody that… Market research has shown us that people want quality, not just low prices.\"\r\n",
    "question_content_prio": 3,
    "quest_content_type": "3",
    "quest_content_groupid": null,
    "quest_content_ui": "1",
    "answer_content": ""
  }
]
